---
title: "Code for Survey Exercise 1"
author: "Alana LaBelle-Hahn" 
date: "01/28/2022"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(readr)
```

``` {r, Importing Data}

leaders <- read_csv("leader_list_8_21.csv")
View(leaders)
```

```{r, Random Sample}
#Taking the first random sample
sample_1 <- leaders %>%
  sample_n(30)

View(sample_1)

# Counting the number of leaders born after 1950
sample_1 %>%
  filter(birthyear) %>%
  count() %>%
  mean(birthyear)

# Finding measure of military career

sample_1 %>%
  filter(militarycareer != "-99") %>%
  group_by(militarycareer) %>%
  count()

# Finding measure of gender
sample_1 %>%
  filter(gender != "-99") %>%
  group_by(gender) %>%
  count()

```


``` {r}

#Taking the second random sample

sample_2 <- leaders %>%
  sample_n(30)

View (sample_2)

#Counting the number of leaders born after 1950

sample_2 %>%
  filter(birthyear >= 1950) %>%
  count()

# Finding measure of military career

sample_2 %>%
  filter(militarycareer != "-99") %>%
  group_by(militarycareer) %>%
  count()

#Finding measure of female to male

sample_2 %>%
  filter(gender != "-99") %>%
  group_by(gender) %>%
  count()

```

